sudo: false  # means that the build doesn't need super user privileges
cache: pip  # means that packages can be cached from pip

language: python

python:
   - "3.6"

install:
   - pip install tox

script:
   - tox

